### PR TITLE
📦 NEW: Docs Page Header

### PR DESCRIPTION
**Pull request by ObaidNadeem**
- Docs page header with Socials and improved Github star button

### CODE REVIEW

**Comment by ahmadawais** [comment]
@ObaidNadeem i think you're using hardcoded svg colors vs currentColor file for icons as on light mode they are no where

image

**Comment by ahmadawais** [comment]
The outline Button looks odd, seems like an issue with thin border?

image

**Comment by ahmadawais** [comment]
@ObaidNadeem can you add them all to the footer as well?

image

**Comment by ahmadawais** [comment]
Responsive design has many issues

image


menu in the middle? looks weird and small

image

**Comment by ObaidNadeem** [comment]
The responsiveness issues were already present, but I’ve resolved them now. ✔️

**Comment by ahmadawais** [comment]
@ObaidNadeem seeing this bar which wasn't the case before

image

**Comment by ahmadawais** [comment]
@ObaidNadeem Logo is not present on mobile 
image

**Comment by ObaidNadeem** [comment]
Yeah here was the default scrollbar, I've applied custom css to that.

**Comment by ObaidNadeem** [comment]
Resolved all issues. There was another issue where the navigation won't work on Tablets/Mobile, fixed that as well.

**Comment by ahmadawais** [comment]
@ObaidNadeem don't think the issues i mentioned are gone. I constantly see the scroll bar. 

image


Please talk to me.

**Comment by ahmadawais** [comment]
@ObaidNadeem this PR has so many irrelevant files, I think the rebase was done in the wrong way. @msaaddev you might need to jump in here.

**Comment by ObaidNadeem** [comment]
image

The scroll bar has always been there. it's just customized version of the old scrollbar.

**Comment by ObaidNadeem** [comment]
I also mentioned this in the previous comment yesterday

**Pull request closed without merging**
